services:
  - type: web
    name: web_news
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn mainsite.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11

    postDeployCommand: "python manage.py migrate"
